# Generated by Django 3.0.6 on 2020-05-15 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='need_refill',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 23, 40, 3, 145563)),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 23, 40, 3, 173743)),
        ),
    ]
