# Generated by Django 3.0.6 on 2020-05-16 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0002_auto_20200515_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='image',
            field=models.FileField(null=True, upload_to='cabinets'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 23, 10, 16, 571318)),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 23, 10, 16, 592934)),
        ),
    ]
