# Generated by Django 3.0.6 on 2020-05-16 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0003_auto_20200516_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='image',
            field=models.FileField(null=True, upload_to='cabinesssts'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 23, 30, 38, 513966)),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 23, 30, 38, 536158)),
        ),
    ]
