# Generated by Django 3.0.6 on 2020-05-16 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0004_auto_20200516_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='image',
            field=models.FileField(null=True, upload_to='cabinets'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 23, 33, 2, 185732)),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 23, 33, 2, 207828)),
        ),
    ]
