# Generated by Django 3.0.6 on 2020-05-16 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0006_auto_20200516_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='image_update',
            field=models.ImageField(null=True, upload_to='cabinets'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 0, 57, 43, 866443)),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 0, 57, 43, 889572)),
        ),
    ]
