# Generated by Django 3.0.6 on 2020-05-16 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0007_auto_20200517_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 2, 54, 36, 317052)),
        ),
        migrations.AlterField(
            model_name='update',
            name='image_update',
            field=models.ImageField(blank=True, null=True, upload_to='cabinets'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 2, 54, 36, 339952)),
        ),
    ]
