# Generated by Django 3.0.6 on 2020-05-19 20:53

import datetime
from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0008_auto_20200517_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 3, 53, 47, 670568)),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 3, 53, 47, 691906)),
        ),
    ]
