# Generated by Django 3.0.6 on 2020-05-19 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0009_auto_20200520_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 3, 59, 42, 905278)),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 3, 59, 42, 926819)),
        ),
    ]
