# Generated by Django 3.0.6 on 2020-05-25 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0010_auto_20200520_0359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 3, 47, 24, 13539)),
        ),
        migrations.AlterField(
            model_name='update',
            name='image_update',
            field=models.ImageField(blank=True, null=True, upload_to='cabinets/uploads'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 3, 47, 24, 49275)),
        ),
    ]
